python -u run.py \
  --task_name anomaly_detection \
  --is_training 1 \
  --root_path ./dataset/SMD \
  --model_id SMD \
  --model DCdetector \
  --data SMD \
  --features M \
  --seq_len 105 \
  --pred_len 0 \
  --d_model 128 \
  --d_ff 128 \
  --e_layers 3 \
  --enc_in 38 \
  --c_out 38 \
  --anomaly_ratio 0.6 \
  --batch_size 256 \
  --train_epochs 2 \
  --gpu 1