python -u run.py \
  --task_name anomaly_detection \
  --is_training 1 \
  --root_path ./dataset/MSL \
  --model_id MSL \
  --model DCdetector \
  --data MSL \
  --features M \
  --seq_len 105 \
  --pred_len 0 \
  --d_model 128 \
  --d_ff 512 \
  --e_layers 3 \
  --enc_in 55 \
  --c_out 55 \
  --anomaly_ratio 1 \
  --batch_size 256 \
  --train_epochs 3 \
  --gpu 1 